<?php $title = "header"; ?>

    <header>

        <div class="logo-title">

            <span class="logo">🎬</span>
            <h1>CinéStream +</h1>

        </div>

            <p>Votre cinéma, partout, a tout moment.</p>
        
        <nav>
            <label for=""></label>
            <a href="index.php?route=index">🎞️</a> 

            <label for=""></label>
            <a href="index.php?route=search">🔎</a>

        </nav>

    </header>

