<?php $title = "index"; ?>

<?php ob_start() ?>

    <!--- boutons catégories --->
    <div class = "categories">

        <a href="?route=index&category=all" class="category <?php if($category == 'all') { echo 'active'; } ?>">
        Tous les films</a>

        <?php foreach($genres as $genre) { ?>

            <a href="?route=index&category=<?=$genre->getId() ?>" class="category <?php if($category == $genre->getId()) { echo 'active'; } ?>">
                <?php echo $genre->getName() ?>
            </a>
        
        <?php } ?>

        <a href="?route=index&category=nc" class="category <?php if($category == 'nc') { echo 'active'; } ?>">n/c</a>
        <a href="?route=index&category=watched" class="category <?php if($category == 'watched') { echo 'active'; } ?>">👁️</a>
        <a href="?route=index&category=towatch" class="category <?php if($category == 'towatch') { echo 'active'; } ?>">🕖</a>
    </div>

    <!--- Grille films --->
    <div class="film-grid">

        <?php if(empty($films)) {?>
            <p class="empty">
                Commence ta vidéothèque en recherchant un film 🔎
            </p>
        <?php } else { ?>
        <?php foreach($films as $film) {?>

            <!--- Cartes films --->
            <a href="index.php?route=show&id=<?= $film->getId() ?>" class="film-card">
                <div class="poster-box">
                    <?php if(!empty($film->getPoster_path())) { ?>
                        <img src="https://image.tmdb.org/t/p/w300<?=htmlspecialchars($film->getPoster_path()) ?>" alt="affiche de <?= htmlspecialchars($film->getTitle()) ?>" class="poster">
                    <?php } else { ?>
                        <div class="no-poster">🎥</div>
                    <?php } ?>   
                </div>

                <div class="info-film-box">
                    <h3><?= htmlspecialchars($film->getTitle()) ?></h3>
                    <p>📅<?= htmlspecialchars($film->getRelease_Date()) ?></p>
                    <span><?= $film->getIsWatched() ? "👁️ Vu" : "🕒 À voir" ?></span>
                </div>  
            </a>
        <?php } ?>
        <?php } ?>
    </div>

<?php $content = ob_get_clean() ?>

<?php require_once __DIR__ . '/base.phtml';